### PR TITLE
Update for esp-idf 4.3 compatibility

### PR DESCRIPTION
**Pull request by jpf91**
Hi,

I really like this project, but I want to use the recent esp-idf 4 releases in my code. It seems that the `_r` functions have been removed from esp-idf, so I changed all calls to the non-`_r` versions. I'd guess the non-`_r` functions exist in older IDF releases as well, so this should probably be backwards compatible?

The changes to `CMakeLists.txt` might be more controversial.  The IDF component system now uses this cmake file. Adding esp-mqtt folder to the component path (even when not using it at all) will already break esp-idf builds, as it tries to parse the  `CMakeLists.txt` as an component and fails. I've changed the file so that esp-mqtt can be used as a drop-in component, but I guess this might break support for esp-idf 3. So if this component is supposed to work with idf 3, we might have to either use different branches or maybe there is some other way to support both in the same code revision.

Tested and working with esp-idf 4.3.

### CODE REVIEW

**Comment by 256dpi** [comment]
Thanks for bringing this up. Retaining compatibility with the old build system would be nice. Was it necessary to remove the "component.mk" file to get it running with CMake?

**Comment by jpf91** [comment]
Good point, it's possible to keep `component.mk`, cmake will ignore it. The only thing that is necessary is changing `CmakeLists.txt`. I've updated the PR.

**Comment by 256dpi** [comment]
Thanks for updating the PR! The "_r" suffixed functions have been a thread-safe variant in the 3.x branch. However, since all network operations are now protected using mutexes I might be ok to revert to the default functions. But, this should be tested with an example program that runs on both cores for a longer amount of time.

**Comment by 256dpi** [comment]
Done!

**Pull request closed without merging**
