### PR TITLE
Add support for setting Last Will and Testament

### PR DESCRIPTION
**Pull request by shmuelzon**

### CODE REVIEW

**Comment by shmuelzon** [comment]
I tried to keep the same coding style as the rest of your project, but let me know if you want me to change anything.

**Comment by 256dpi** [comment]
Awesome! Thank you very much!

The only thing I would add is a little reminder that this functions should be called before `esp_mqtt_start`.

Did you successfully test your change?

**Comment by 256dpi** [comment]
Oh and could you update the `README.md` as well? :-)

**Comment by shmuelzon** [comment]
> The only thing I would add is a little reminder that this functions should be called before esp_mqtt_start.

Done.

> Oh and could you update the README.md as well? :-)

Done.

>Did you successfully test your change?

Yes, on v0.4.4. I tried to update my code to use v0.5.0 but the connection kept disconnecting. LWT did work though as with each disconnection the broker sent the LWT message but I still need to check why it keeps disconnecting.

**Comment by 256dpi** [comment]
Cool thanks!

**Comment by 256dpi** [comment]
I cut a new release: https://github.com/256dpi/esp-mqtt/releases/tag/v0.5.1

**Pull request merged**
