### PR TITLE
Add tls connection type support

### PR DESCRIPTION
**Pull request by kshyshkin**
Hello Joël. I implement secure connection to your component by mbedtls. Please see it. I will be glad to your comments.

Thank you for advance.
Best regards, Konstantin Shyshkin.

### CODE REVIEW

**Comment by 256dpi** [comment]
Dear Konstantin, that's amazing! Thanks so much. 

I quickly skimmed through the code and it looks good. Howevery,  I need to take a free evening to go through it line by line, especially the mbedtls API calls.

There is one bigger improvement I would like to discuss: If possible I would like to design the `esp-mqtt` in such a way that the user can easily change between an unsecure and secured connection. Therefore, I would not use compile time switches to select TLS. I have an application myself, that can be configured on runtime and thus SSL would also be enabled/disabled on runtime.

I would propose to add the following method:

```c++
// This method must be called before `esp_mqtt_start` to setup TLS if needed.
void esp_mqtt_tls(bool enabled, bool verify, const char * cacert);
```

In the future the library should support the use of multiple clients, thus with this API we could even offer unsecure and secure clients to coexist at the same time.

What do you think?

**Comment by kshyshkin** [comment]
Hello Joël. It is good idea. I think we can do 3 mode.
1. Default mode  : Tls disable, minimum stack size, minimum firmware size.
2. CONFIG_ESP_MQTT_TLS_ENABLE : Both type of connection available, secure through tls, and unsecure.
3.CONFIG_ESP_MQTT_TLS_ONLY : Only tls connection available.
I would happy implement this by myself, you can leave comments in code, and i do it. What do you think about this?

Thank you for advance.
Best regards, Konstantin Shyshkin.

**Comment by 256dpi** [comment]
I like your suggestion! I would recommend to set `CONFIG_ESP_MQTT_TLS_ENABLE` as the default since the other options disable functionality, which targets more advanced users.

**Comment by kshyshkin** [comment]
Ok, thank you. I need some time to implement this solution. After i do this, i will commit changes and write to you here.

Thank you for advance.
Best regards, Konstantin Shyshkin.

**Comment by kshyshkin** [comment]
Hello Joël. I finish add 3 different mode as we discus with you. Will be waiting your comments.

Thank you for advance.
Best regards, Konstantin Shyshkin.

**Comment by 256dpi** [comment]
Thanks for your work. It looks very good. Very nice of you to add all the examples. 👍 

Some comments:

- I can understand that it makes sense to disable the compilation of the TLS stuff if not needed. But, does it make sense to disable the compilation of the non TLS implementation? I assume MbedTLS uses the LWIP API as well and it gets linked anyway? I would, if possible, remove the `ESP_MQTT_TLS_ONLY` setting.

- Can we add a `bool enable` parameter to `esp_mqtt_tls()`? It would be cool to have the ability to enable. and disable TLS on runtime.

- Here I'm just curious: Whats the calculation for the `9216` stack size of the esp-mqtt task?

I'll be able to test the implementation next week and give further feedback.

**Comment by justdominator** [comment]
@256dpi Hi Joël. Will try to answer 

1. According to unsecured mode:
 - We also have different MQTT backends, but all of them are secured. Left unsecured code part just overhead for us.
 - Also there are some security policies on our customers side, they can review our solution and it will good when our device can't connect insecurely at all 

2. Related to first sentence. In runtime, I think just easier do not call esp_mqtt_tls() in case of switching to insecure connection

3. https://tls.mbed.org/discussions/generic/ram-requirements

BR

**Comment by justdominator** [comment]
@256dpi Hello Joël. Are there some updates according to review the PR?

**Comment by justdominator** [comment]
Kostya.
Looks like our PR not interested. Will close it within two days if we don't receive some feedback. Ok?

**Comment by justdominator** [comment]
@256dpi we can maintain and support your project or another one. Please, make decision. You didn't have provided any feedback in ETA, it's sad.

**Comment by 256dpi** [comment]
Sorry, I'm very busy ATM. I'll take a look at this soon. Please be aware that I work on this projects in my free-time and thus other things take priority.

**Comment by 256dpi** [comment]
FYI: Your patch has been merged with some small modifications. Thanks again for the contribution!

**Comment by kshyshkin** [comment]
Thanks.

**Pull request closed without merging**
